Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new,:create, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands

end

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_App/app/models/band.rb
class Band < ApplicationRecord
validates :name, presence: true


end

Music_App/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true 
    validates :password_digest, presence: true

    attr_reader :password

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    before_validation :ensure_session_token

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password

    end

    def check_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

   

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        if user && user.check_password?(password)
            user
        else
            nil
        end
    end













end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end

    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end

    def update
        band = Band.find(params[:id])

        if band.update(band_params)
            redirect_to band_url(band)
        else
            render json: errors.full_messages, status: 422
        end
    end

    def destroy
        band = Band.find(params[:id])

        band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end




end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new 
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ["Invalid Credentials"]
            redirect_to new_session_url
        end



    end







end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def new 
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @users.errors.full_messages
            render :new
        end


    end

    def edit 
        @user = User.find_by(id: params[:id])
        render :edit
    end

    def update
        user = User.find(params[:id])

        if user.update(user_params)
            redirect_to user_url(user)
        else
            render json: errors.full_messages, status: 422
        end
    end

    def destroy
        user = User.find(params[:id])

        user.destroy
        redirect_to users_url

    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper
end

Music_App/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

Music_App/app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>

    <% @bands.each do |band| %>
    <li class = "bandname">
    <%= band.name%>
    <% end %>
    </li>





</ul>

Music_App/app/views/bands/new.html.erb
<h1> Add Band </h1>

<form action="<%= bands_url %>" method="POST">
    <label for="name"> Band Name</label>
    <input type="text" id="name" name="band[name]" value="<%= @band.name %>">
    <br>
    <button> Add Band </button>

</form>

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in?%>
      <h2>Welcome <%= current_user.username%></h2>
    <% else %>
      <a href="<%= new_session_url%>"> Login </a>
      <br>
      <a href="<%= new_user_url%>"> Signup</a>
    <%end%>

    <%= yield %>
  </body>
</html>

Music_App/app/views/users/new.html.erb
<h1> Sign up </h1>

<input type = "hidden" value = "<%= form_authenticity_token %>">

<form action="<%= users_url %>" method="POST">
    <label for="email"> email</label>
    <input type="text" id="email" name="user[email]" value="<%= @user.email %>">
    <br>
    <label for="password">Password</label>
    <input type= "password" id="password" name="user[password]" value="<%= @user.email %>">

    <button> Sign up</button>

</form>